# Generated by Django 5.1.1 on 2024-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OC6', 'OC6'), ('V6', 'V6'), ('OC2', 'OC2'), ('V2', 'V2'), ('OC1', 'OC1'), ('V1', 'V1'), ('TUR', 'Turismo'), ('OCI', 'Oceânico Individual'), ('OCD', 'Oceânico Duplo'), ('LFS', 'Lifesaving'), ('SFKI', 'Surfski Individual'), ('SFKD', 'Surfski Duplo'), ('PCD', 'Para-Canoagem')], max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
