# Generated by Django 5.1.1 on 2024-10-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starts', '0005_alter_start_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='category',
            field=models.CharField(choices=[('OC6', ''), ('GERAL', ''), ('JUNIORES', '')], max_length=10, unique=True),
        ),
    ]
