# Generated by Django 5.1.1 on 2024-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vest_number', models.IntegerField()),
                ('arrival_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
