# Generated by Django 5.1.1 on 2024-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0002_alter_arrival_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
