# Generated by Django 5.1.1 on 2024-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0003_alter_arrival_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
