# Generated by Django 5.1.1 on 2024-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0004_alter_arrival_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='vest_number',
            field=models.IntegerField(unique=True),
        ),
    ]
