# Generated by Django 5.1.1 on 2024-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=100)),
                ('car_identification', models.CharField(max_length=7)),
                ('car_model', models.CharField(max_length=200)),
                ('cars_per_team', models.IntegerField()),
            ],
        ),
    ]
