# Generated by Django 5.1.1 on 2024-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_identification',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
