# Generated by Django 5.1.1 on 2024-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_identification',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
