# Generated by Django 5.1.1 on 2024-09-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name6',
        ),
    ]
