# Generated by Django 5.1.1 on 2024-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_remove_entry_name2_remove_entry_name3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='name3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='name4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='name5',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='name6',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
