# Generated by Django 5.1.1 on 2024-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_name2_entry_name3_entry_name4_entry_name5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name1',
            field=models.CharField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
