# Generated by Django 5.1.1 on 2024-10-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='boat_class',
            field=models.CharField(choices=[('OC6', 'OC6'), ('V6', 'V6'), ('OC2', 'OC2'), ('V2', 'V2'), ('OC1', 'OC1'), ('V1', 'V1'), ('TUR', 'Turismo'), ('OCI', 'Oceanico individual'), ('OCD', 'Oceanico duplo'), ('LFS', 'Lifesaving'), ('SFKI', 'Surfski individual'), ('SFKD', 'Surfski duplo'), ('PCD', 'Para-canoagem')], max_length=10),
        ),
    ]
