# Generated by Django 5.1.1 on 2024-10-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_alter_entry_age_category_alter_entry_boat_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='vest_number',
            field=models.IntegerField(unique=True),
        ),
    ]
